/**
 * Persisted list of `DocumentReminder`s. Drives the Documents tab UI and
 * the `useReminderSync` hook that wires entries to local notifications.
 *
 * `id` is generated by expo-crypto. Capped at MAX_DOCUMENTS to keep the
 * editor list bounded; the sync hook also has finite scheduling capacity.
 */

import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Crypto from 'expo-crypto';
import { create } from 'zustand';
import { createJSONStorage, persist } from 'zustand/middleware';

import type { DocumentKind, DocumentReminder } from '@/types/document';

export const MAX_DOCUMENTS = 30;

export const DEFAULT_NOTIFY_DAYS = [30, 7, 1] as const;

export interface AddDocumentResult {
  added: boolean;
  document?: DocumentReminder;
  reason?: 'limit_reached';
}

interface DocumentsStore {
  documents: DocumentReminder[];
  addDocument: (input: {
    kind: DocumentKind;
    expiryDate: string;
    customName?: string;
    notifyDaysBefore?: number[];
    notes?: string;
  }) => AddDocumentResult;
  updateDocument: (id: string, partial: Partial<Omit<DocumentReminder, 'id'>>) => void;
  removeDocument: (id: string) => void;
  clearAll: () => void;
  getDocument: (id: string) => DocumentReminder | undefined;
}

export const useDocumentsStore = create<DocumentsStore>()(
  persist(
    (set, get) => ({
      documents: [],

      addDocument: (input) => {
        const current = get().documents;
        if (current.length >= MAX_DOCUMENTS) {
          return { added: false, reason: 'limit_reached' };
        }
        const doc: DocumentReminder = {
          id: Crypto.randomUUID(),
          kind: input.kind,
          expiryDate: input.expiryDate,
          notifyDaysBefore:
            input.notifyDaysBefore && input.notifyDaysBefore.length > 0
              ? input.notifyDaysBefore
              : [...DEFAULT_NOTIFY_DAYS],
          ...(input.customName ? { customName: input.customName } : {}),
          ...(input.notes ? { notes: input.notes } : {}),
        };
        set({ documents: [...current, doc] });
        return { added: true, document: doc };
      },

      updateDocument: (id, partial) => {
        set({
          documents: get().documents.map((d) => (d.id === id ? { ...d, ...partial } : d)),
        });
      },

      removeDocument: (id) => {
        set({ documents: get().documents.filter((d) => d.id !== id) });
      },

      clearAll: () => set({ documents: [] }),

      getDocument: (id) => get().documents.find((d) => d.id === id),
    }),
    {
      name: 'kakei-documents-v1',
      storage: createJSONStorage(() => AsyncStorage),
      partialize: (state) => ({ documents: state.documents }),
    },
  ),
);
